# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa0bdcd27925e57e1b37a5d571fd36aa7cbee6dc5853b1a351507051fb4969681ad5784a3bc62ea8e8c1aeaa6580427c4c44010ae7c579314213fdf6273a9231

test:
  secret_key_base: 4c813a5473a5cf99c43c3d1c00d89eaf522a65fd17aa527db9055d0a8fad0d3d88da93462b8e8022d3e2ad8fd3c732cd1cfc52bc7d69b8f25ef77a2657d5676d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
